name: CI Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: php:7.3-apache
      env:
        NODE_ENV: production
      ports:
      - 80
      volumes:
      - ${{ github.workspace }}:/var/www/html
    services:
      mysql:
        image: mysql:5.7.27
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306
        volumes:
        - /github/home/mysql:/var/lib/mysql
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Debug
      run: |
        echo ${{ github.workspace }}
        echo ${{ env.HOME }}